version: '3'

services:
  keva:
    # image: keva:pg
    # ports:
    #   - "8080:8080"
    # networks:
    #   - kevaNetwork
    
    postgres:
      image: postres:14
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWRD=pa55workd
        - POSTGRES_DB=keva
      # networks:
      #   - kevaNetwork
    
# networks:
#   kevaNetwork: